# Generated by Django 3.2 on 2022-08-13 09:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notices', models.TextField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.group')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
                'db_table': 'notice_table',
            },
        ),
        migrations.CreateModel(
            name='Fantweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=50, verbose_name='작성자')),
                ('author_id', models.CharField(blank=True, max_length=15, verbose_name='작성자 id')),
                ('date', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000000)], verbose_name='작성 날짜')),
                ('retweets', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='리트윗')),
                ('replies', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='답장')),
                ('hearts', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='좋아요')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.group')),
            ],
            options={
                'verbose_name': '팬트윗',
                'verbose_name_plural': '팬트윗',
                'db_table': 'fantweet_table',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=50, verbose_name='작성자')),
                ('author_id', models.CharField(blank=True, max_length=15, verbose_name='작성자 id')),
                ('date', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000000)], verbose_name='작성 날짜')),
                ('retweets', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='리트윗')),
                ('replies', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='답장')),
                ('hearts', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='좋아요')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='사진')),
                ('gifs', models.FileField(blank=True, null=True, upload_to='gifs', verbose_name='gif')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.group')),
            ],
            options={
                'verbose_name': '콘텐츠',
                'verbose_name_plural': '콘텐츠',
                'db_table': 'content_table',
            },
        ),
    ]
