# Generated by Django 3.2 on 2022-08-15 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '__first__'),
        ('imageSearch', '0002_auto_20220816_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupnotification',
            name='refergroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.group', verbose_name='Group.__str__공식일정'),
        ),
    ]
